[package]
name = "datafusion-schema-evolution-exmaple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.41"
datafusion = "6.0.0"
arrow = "6.0.0"
tokio = "1.0"
